var data = {
    title: 'BIỂU ĐỒ LỊCH SỬ ĐÁNH GIÁ 360',
    titleFont: '20pt Myriad Pro',
    titleStyle: 'red',
    xLabel: 'Tên dự án',
    yLabel: 'Điểm đánh giá 360',
    labelFont: 'italic 12pt Adobe Ming Std L',
    labelStyle: '#000000',
    axisFont: '15pt Myriad Pro',
    axisStyle: '#000000',
    commentStyle: '#000000',
    splineStyle: '#019ed5',
    maxNumberYAxic: 10,
    dataPoints: [{ x: 'A', y: 2.3 },
                { x: 'B', y: 1 },
                { x: 'C', y: 3.5 },
                { x: 'D', y: 4.1 },
                { x: 'E', y: 3 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 4 },
                { x: 'F', y: 2 }]
};